# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=False)),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='images/blog')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
