# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
