# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170802_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lookup',
            new_name='slug',
        ),
    ]
